=encoding utf-8

=head1 名前

twept - (主に)HTMLのためのPerlコード埋め込み I<(テストとデバッグ用)>

=head1 概要

最初の行へと挿入します。

  #!/あなたの/パス/twepl

=head1 説明

(主に)HTMLのためのPerlコード埋め込み、それは簡素で容易です。

I<E<lt>$ Perl-Code $E<gt>> をHTMLへ追加します。
またコードブロックが多数あれば、コードブロック間で局所化された変数は使用できません。

出力HTMLにてコードが見えます。
エラーが見つかっても強制終了しません。
(強制終了はループ検出自のみ)

=head1 タイムアウト

ループを検知すると強制終了します。
必要ならグローバル変数 B<$TIMEOUT> を上書きして変更してください。

  # 初期設定は E<quot>2E<quot> 秒です
  $TIMEOUT = 2;

alarm の下で既に実行されて、そのタイムアウトの変更はできません。

  # 新規タイムアウトとして
  alarm(B<X>);

=head1 予約済み変数

  $TIMEOUT(グローバル)
  $epl
  $var

=head1 オプション

tweptのためのオプションは何もありません。

=head1 著者

トゥインクル・コンピューティング <twinkle@cpan.org>

=cut
