=head1 NAME

twept - The Perl embeddings for HTML. I<(for test and debug)>

=head1 SYNOPSYS

inserting first line to

  #!/your/path/twepl

=head1 DESCRIPTION

The Perl-Code embeddings for HTML, it is simple and easy.

adding I<E<lt>$ Perl-Code $E<gt>> to your HTML.
if code blocks too many, cannot use local variables between code blocks.

visible your code in the output HTML.
not force exiting on found errors.
(forced exiting E<quot>detected loopE<quot> only)

=head1 OPTIONS

nothing options for twept

=head1 SEE ALSO

L<HTML::EmbeddedPerl::Test>

=head1 AUTHOR

Twinkle Computing <twinkle@cpan.org>

=head1 LISENCE

Copyright (c) 2010 Twinkle Computing All rights reserved.

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
